apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysqldb
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: centos
        - name: MYSQL_USER
          value: myuser1
        - name: MYSQL_PASSWORD
          value: myuserpass
        - name: MYSQL_DATABASE
          value: blr
        ports:
        - containerPort: 3306
          name: mysql
